export const PROFILES = [
  {
    id: 1,
    mat_id: 'M1234567',
    name: 'Priyanka',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
  },
  {
    id: 2,
    mat_id: 'M1234567',
    name: 'Monica',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
  },
  {
    id: 3,
    mat_id: 'M1234567',
    name: 'Divya',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
  },
  {
    id: 4,
    mat_id: 'M1234567',
    name: 'Grace',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
  },
  {
    id: 5,
    mat_id: 'M1234567',
    name: 'Shalini',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
  },
  {
    id: 6,
    mat_id: 'M1234567',
    name: 'Swetha',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
  },
  {
    id: 7,
    mat_id: 'M1234567',
    name: 'Raja Laxmi',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
  },
  {
    id: 8,
    mat_id: 'M1234567',
    name: 'Aishwarya',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
  },
  {
    id: 9,
    mat_id: 'M1234567',
    name: 'Jona',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
  },
  {
    id: 10,
    mat_id: 'M1234567',
    name: 'Catherine',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
  },
];
