export const RECOMMENDED_PROFILES = [
  {
    id: 1,
    mat_id: 'M1234567',
    name: 'Priyanka',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
    spirituality: 'Born Again',
  },
  {
    id: 2,
    mat_id: 'M1234567',
    name: 'Monica',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'B.Com',
    profession: 'Accountant',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
    spirituality: 'Born Again',
  },
  {
    id: 3,
    mat_id: 'M1234567',
    name: 'Divya',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'BE',
    profession: 'Human Resource Professional',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
    spirituality: 'Born Again',
  },
  {
    id: 4,
    mat_id: 'M1234567',
    name: 'Grace',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'BEd',
    profession: 'Teacher',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
    spirituality: 'Spiritual',
  },
  {
    id: 5,
    mat_id: 'M1234567',
    name: 'Shalini',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
    spirituality: 'Born Again',
  },
  {
    id: 6,
    mat_id: 'M1234567',
    name: 'Swetha',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
    spirituality: 'Spiritual',
  },
  {
    id: 7,
    mat_id: 'M1234567',
    name: 'Raja Laxmi',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'BCA',
    profession: 'Administrator',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
    spirituality: 'Born Again',
  },
  {
    id: 8,
    mat_id: 'M1234567',
    name: 'Aishwarya',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'BSc',
    profession: 'Teacher',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
    spirituality: 'Spiritual',
  },
  {
    id: 9,
    mat_id: 'M1234567',
    name: 'Jona',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MCA',
    profession: 'Software Developer',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
    spirituality: 'Spiritual',
  },
  {
    id: 10,
    mat_id: 'M1234567',
    name: 'Catherine',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBA',
    profession: 'Manager',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    img: 'assets/profile-image-female.jpg',
    spirituality: 'Spiritual',
  },
];
