export const RECOMMENDED_PROFILES = [
  {
    id: 'M1234567',
    name: 'Priyanka',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
  },
  {
    id: 'M1234567',
    name: 'Monica',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
  },
  {
    id: 'M1234567',
    name: 'Divya',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
  },
  {
    id: 'M1234567',
    name: 'Grace',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
  },
  {
    id: 'M1234567',
    name: 'Shalini',
    age: '27 Yrs',
    height: '5 ft 2 in',
    motherTongue: 'Tamil',
    community: 'Nair',
    education: 'MBBS',
    profession: 'Doctor',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
  },
];
